---
deployment:
  tasks:
    - echo "🔧 Installing dependencies"
    - npm ci
    - echo "🏗️  Building production bundle"
    - npm run build
    - echo "🚚 Deploying to public_html"
    - rm -rf /home/cusop751wkat/public_html/*
    - cp -r dist/* /home/cusop751wkat/public_html
